### ISSUE TITLE
Clarification for similarity measures

### ISSUE THREAD

**Issue by haoteli** [bengioe/gflownet#10]
Dear Authors,

It was exciting to read about your methods and results for molecule generation applications! I have a few questions below and hope that you can provide more details.

In the article, you mentioned that the top 1000 molecules' mean pairwise Tanimoto similarities were calculated.
1. Could you please specify the type of fingerprint(s) that are used for the Tanimoto similarity calculation? 

2. In addition, does the mean pairwise similarity mean taking each molecule in the set and calculating its similarity to all the other molecules in the set, repeating this procedure for all the other molecules then taking the mean of all the means?

I wasn't able to locate any code/comments relating to this part specifically.  I would greatly appreciate it if you can point me to the codes as well!

Regards,

Haote

**Comment by bengioe** [comment]
Hi Haote,

1. We used the default fingerprinting available in RDKit, `Chem.RDKFingerprint`, although you should get similar numbers using the standard ECFP4 fingerprints.
2. Yes that is correct, this can be achieved efficiently using `rdkit.DataStructs.BulkTanimotoSimilarity`.

We indeed did not upload the analysis scripts, they were embedded in a mess of notebooks and we did not take the time to extract them out. Let us know if you have additional questions.

**Comment by haoteli** [comment]
Thank you very much! That resolves all my questions!
