### ISSUE TITLE
questions about modes found

### ISSUE THREAD

**Issue by yuxuan9982** [bengioe/gflownet#19]
I have a question about my understanding. I thought that 'modes found' should be an integer, but the figure in the paper shows that 'modes found' can be a decimal. Does modes found mean areas with scores 2.5 in gridworld?

**Comment by bengioe** [comment]
Hi @yuxuan9982, mode counts are indeed integers, the decimals from the paper plots may come from averaging these integers over multiple run. In the grid example, mode states are states with [reward 2](https://github.com/GFNOrg/gflownet/blob/master/grid/toy_grid_dag.py#L76).

**Comment by yuxuan9982** [comment]
ok, thanks
