### ISSUE TITLE
Reward signal for grid environment?

### ISSUE THREAD

**Issue by SamKG** [bengioe/gflownet#6]
Hello,
I'm a bit confused where this reward function comes from: https://github.com/GFNOrg/gflownet/blob/831a6989d1abd5c05123ec84654fb08629d9bc38/grid/toy_grid_dag.py#L97

My understanding is that the reward should be as defined in the paper (https://i.samkg.dev/2233/firefox_xGnEaZVBlN.png) - are these two equivalent in some way?

**Comment by bengioe** [comment]
Hello, this is indeed the default for the `GridEnv` class, but the default for the experiment is `'corners'`, as in the paper, which is defined a bit a above:

https://github.com/GFNOrg/gflownet/blob/831a6989d1abd5c05123ec84654fb08629d9bc38/grid/toy_grid_dag.py#L74-L76
